//! `artifacts/audit/latest.json` audit snapshot (master plan §0.1.2).
//!
//! The snapshot freezes the machine-verifiable inputs of a phase run: input
//! SHA, remote heads, dirty-path manifest, CI run reference, raw command
//! exits and generation time. It is **generated by scripts, never hand-edited**
//! — the write path refuses missing mandatory fields, and the read path
//! re-validates them so a hand-edited or torn snapshot fails closed.

use std::path::Path;

pub const AUDIT_SNAPSHOT_SCHEMA_VERSION: u16 = 1;

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct AuditSnapshotV1 {
    pub schema_version: u16,
    /// ISO-8601 UTC generation time — mandatory.
    pub generated_at: String,
    /// Full input SHA-1 of the audited HEAD — mandatory.
    pub git_head: String,
    /// `name=sha` lines for remote branch heads at generation time.
    pub remote_heads: Vec<String>,
    /// Dirty-path manifest (untracked/modified paths) at generation time.
    pub dirty_path_manifest: Vec<String>,
    /// CI run reference (e.g. `https://github.com/.../actions/runs/123`) or
    /// `NOT_RUN` when no exact-SHA run exists.
    pub ci_run: String,
    /// Raw command exit codes: `name=exit` lines, one per observed command.
    pub command_exits: Vec<String>,
    /// sha256 of SOURCE_LOCK.json at generation time, or `NOT_RUN`.
    pub source_lock_sha256: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AuditSnapshotDeny {
    Invalid(String),
    MissingField(&'static str),
    SchemaMismatch,
    NotReadable(String),
}

impl AuditSnapshotDeny {
    pub fn code(&self) -> &'static str {
        match self {
            Self::Invalid(_) => "audit.invalid",
            Self::MissingField(_) => "audit.missing_field",
            Self::SchemaMismatch => "audit.schema_mismatch",
            Self::NotReadable(_) => "audit.not_readable",
        }
    }
}

impl std::fmt::Display for AuditSnapshotDeny {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Invalid(msg) => write!(f, "{}: {msg}", self.code()),
            Self::MissingField(name) => write!(f, "{}: {name}", self.code()),
            Self::NotReadable(msg) => write!(f, "{}: {msg}", self.code()),
            other => write!(f, "{}", other.code()),
        }
    }
}

impl AuditSnapshotV1 {
    /// Validate every mandatory field. Any missing/blank field is a hard
    /// failure — the write path refuses, the read path rejects.
    pub fn validate(&self) -> Result<(), AuditSnapshotDeny> {
        if self.schema_version != AUDIT_SNAPSHOT_SCHEMA_VERSION {
            return Err(AuditSnapshotDeny::SchemaMismatch);
        }
        for (name, value) in [
            ("generated_at", self.generated_at.as_str()),
            ("git_head", self.git_head.as_str()),
            ("ci_run", self.ci_run.as_str()),
            ("source_lock_sha256", self.source_lock_sha256.as_str()),
        ] {
            if value.trim().is_empty() {
                return Err(AuditSnapshotDeny::MissingField(name));
            }
        }
        if self.git_head.len() != 40 {
            return Err(AuditSnapshotDeny::Invalid(
                "git_head must be a full 40-char SHA-1".into(),
            ));
        }
        for exit in &self.command_exits {
            let Some((name, code)) = exit.split_once('=') else {
                return Err(AuditSnapshotDeny::Invalid(format!(
                    "command_exit entry {exit:?} must be name=exit"
                )));
            };
            if name.trim().is_empty() || !code.chars().all(|c| c.is_ascii_digit()) {
                return Err(AuditSnapshotDeny::Invalid(format!(
                    "command_exit entry {exit:?} must be name=<exit code>"
                )));
            }
        }
        Ok(())
    }

    /// Write the snapshot atomically (tempfile + rename). Refuses to write an
    /// invalid snapshot — a hand-built snapshot missing fields can never land.
    pub fn write_to(&self, path: &Path) -> Result<(), AuditSnapshotDeny> {
        self.validate()?;
        let parent = path.parent().ok_or_else(|| {
            AuditSnapshotDeny::NotReadable("snapshot path has no parent".into())
        })?;
        std::fs::create_dir_all(parent)
            .map_err(|e| AuditSnapshotDeny::NotReadable(e.to_string()))?;
        let json = serde_json::to_string_pretty(self)
            .map_err(|e| AuditSnapshotDeny::Invalid(e.to_string()))?;
        let tmp = parent.join(format!(
            ".latest.json.tmp-{}",
            std::process::id()
        ));
        std::fs::write(&tmp, json + "\n")
            .map_err(|e| AuditSnapshotDeny::NotReadable(e.to_string()))?;
        std::fs::rename(&tmp, path)
            .map_err(|e| AuditSnapshotDeny::NotReadable(e.to_string()))
    }

    /// Read and validate an existing snapshot. A torn, hand-edited or
    /// missing-field snapshot fails closed.
    pub fn read_from(path: &Path) -> Result<Self, AuditSnapshotDeny> {
        let raw = std::fs::read_to_string(path)
            .map_err(|e| AuditSnapshotDeny::NotReadable(e.to_string()))?;
        let snapshot: AuditSnapshotV1 = serde_json::from_str(&raw)
            .map_err(|e| AuditSnapshotDeny::NotReadable(e.to_string()))?;
        snapshot.validate()?;
        Ok(snapshot)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_snapshot() -> AuditSnapshotV1 {
        AuditSnapshotV1 {
            schema_version: AUDIT_SNAPSHOT_SCHEMA_VERSION,
            generated_at: "2026-08-04T12:00:00Z".into(),
            git_head: "d74db8e0a415911ad3c6eb859c8424888edf3499".into(),
            remote_heads: vec!["main=d74db8e0a415911ad3c6eb859c8424888edf3499".into()],
            dirty_path_manifest: vec![],
            ci_run: "https://github.com/exergyleizhou-ux/lumen/actions/runs/30898108031".into(),
            command_exits: vec!["offline_gates=0".into(), "gitleaks=0".into()],
            source_lock_sha256: "2b7c5e8faabc241880da70b230bf7d5afe3a249616ffdad74d4b53514ebe69ba"
                .into(),
        }
    }

    #[test]
    fn snapshot_roundtrip_write_read_validate() {
        let dir = tempfile::tempdir().expect("tmp");
        let path = dir.path().join("latest.json");
        let snapshot = sample_snapshot();
        snapshot.write_to(&path).expect("write");
        let back = AuditSnapshotV1::read_from(&path).expect("read");
        assert_eq!(back, snapshot);
    }

    #[test]
    fn snapshot_refuses_missing_mandatory_fields() {
        let mut snapshot = sample_snapshot();
        snapshot.git_head = "".into();
        assert_eq!(
            snapshot.validate().unwrap_err(),
            AuditSnapshotDeny::MissingField("git_head")
        );
        let mut snapshot = sample_snapshot();
        snapshot.ci_run = "".into();
        assert_eq!(
            snapshot.validate().unwrap_err(),
            AuditSnapshotDeny::MissingField("ci_run")
        );
        let mut snapshot = sample_snapshot();
        snapshot.generated_at = "".into();
        assert_eq!(
            snapshot.validate().unwrap_err(),
            AuditSnapshotDeny::MissingField("generated_at")
        );
    }

    #[test]
    fn snapshot_rejects_short_head_and_bad_exit_entries() {
        let mut snapshot = sample_snapshot();
        snapshot.git_head = "d74db8e0".into();
        assert_eq!(snapshot.validate().unwrap_err().code(), "audit.invalid");
        let mut snapshot = sample_snapshot();
        snapshot.command_exits = vec!["not-an-exit".into()];
        assert_eq!(snapshot.validate().unwrap_err().code(), "audit.invalid");
        let mut snapshot = sample_snapshot();
        snapshot.command_exits = vec!["name=abc".into()];
        assert_eq!(snapshot.validate().unwrap_err().code(), "audit.invalid");
    }

    #[test]
    fn write_refuses_invalid_snapshot() {
        let dir = tempfile::tempdir().expect("tmp");
        let path = dir.path().join("latest.json");
        let mut snapshot = sample_snapshot();
        snapshot.source_lock_sha256 = "".into();
        snapshot.write_to(&path).expect_err("must refuse");
        assert!(!path.exists(), "invalid snapshot must not land on disk");
    }

    #[test]
    fn read_rejects_hand_edited_snapshot() {
        let dir = tempfile::tempdir().expect("tmp");
        let path = dir.path().join("latest.json");
        sample_snapshot().write_to(&path).expect("write");
        // Simulate a hand-edit removing a mandatory field.
        let raw = std::fs::read_to_string(&path).expect("read");
        let trimmed = raw
            .lines()
            .filter(|line| !line.contains("git_head"))
            .collect::<Vec<_>>()
            .join("\n");
        std::fs::write(&path, trimmed).expect("rewrite");
        AuditSnapshotV1::read_from(&path).expect_err("hand-edited snapshot fails closed");
    }
}
