#!/usr/bin/env bash
# Start local Lab with optional sidecars (LangGraph + OnlyOffice if ready).
# Usage:
#   ./scripts/science/lab-local-with-sidecars.sh
#   ADDR=0.0.0.0:18992 ./scripts/science/lab-local-with-sidecars.sh
#   SMOKE=1 ./scripts/science/lab-local-with-sidecars.sh   # start, check health, exit
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ADDR="${ADDR:-0.0.0.0:18992}"
LUMEN_HOME="${LUMEN_HOME:-$HOME/.lumen}"
VENV="${LUMEN_LANGGRAPH_VENV:-$LUMEN_HOME/langgraph-venv}"
SCRIPT="${LUMEN_LANGGRAPH_SCRIPT:-$LUMEN_HOME/langgraph_runner.py}"
OO_PORT="${ONLYOFFICE_PORT:-8088}"
ENV_FILE="${LUMEN_SIDECARS_ENV:-$LUMEN_HOME/lab-sidecars.env}"
# Prefer repo build when LUMEN_USE_INSTALLED is not set (avoids stale ~/.local/bin/lumen).
USE_INSTALLED="${LUMEN_USE_INSTALLED:-0}"

export PATH="${HOME}/.local/bin:${PATH}"

# LangGraph: enable only if venv can import langgraph
if [[ -x "$VENV/bin/python3" ]] && "$VENV/bin/python3" -c "import langgraph" 2>/dev/null; then
  export LUMEN_LANGGRAPH=1
  export LUMEN_LANGGRAPH_VENV="$VENV"
  export LUMEN_LANGGRAPH_SCRIPT="$SCRIPT"
  echo "[lab-local] LangGraph enabled ($VENV)"
else
  unset LUMEN_LANGGRAPH || true
  echo "[lab-local] LangGraph not ready (run scripts/science/setup-langgraph.sh)"
fi

# OnlyOffice: enable if something answers on local port
if curl -sS -o /dev/null -w "%{http_code}" "http://127.0.0.1:${OO_PORT}/" 2>/dev/null | grep -Eq '200|301|302'; then
  export LUMEN_ONLYOFFICE_URL="http://127.0.0.1:${OO_PORT}"
  echo "[lab-local] OnlyOffice enabled ($LUMEN_ONLYOFFICE_URL)"
else
  unset LUMEN_ONLYOFFICE_URL || true
  echo "[lab-local] OnlyOffice not listening on :${OO_PORT} (run scripts/science/setup-onlyoffice.sh)"
fi

# Persist env for other shells / IDE launches
mkdir -p "$LUMEN_HOME"
{
  echo "# Generated by lab-local-with-sidecars.sh — source this file to enable sidecars"
  echo "# $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  if [[ "${LUMEN_LANGGRAPH:-}" == "1" ]]; then
    echo "export LUMEN_LANGGRAPH=1"
    echo "export LUMEN_LANGGRAPH_VENV=\"$VENV\""
    echo "export LUMEN_LANGGRAPH_SCRIPT=\"$SCRIPT\""
  else
    echo "unset LUMEN_LANGGRAPH"
  fi
  if [[ -n "${LUMEN_ONLYOFFICE_URL:-}" ]]; then
    echo "export LUMEN_ONLYOFFICE_URL=\"$LUMEN_ONLYOFFICE_URL\""
  else
    echo "unset LUMEN_ONLYOFFICE_URL"
  fi
} >"$ENV_FILE"
echo "[lab-local] wrote $ENV_FILE"

cd "$REPO_ROOT"

run_lab() {
  if [[ "$USE_INSTALLED" == "1" ]] && command -v lumen >/dev/null 2>&1; then
    echo "[lab-local] using installed lumen ($(command -v lumen))"
    exec lumen science lab --addr "$ADDR" --no-browser
  fi
  if command -v go >/dev/null 2>&1 && [[ -d "$REPO_ROOT/cmd/lumen" ]]; then
    echo "[lab-local] using go run ./cmd/lumen (set LUMEN_USE_INSTALLED=1 for binary)"
    exec go run ./cmd/lumen science lab --addr "$ADDR" --no-browser
  fi
  if command -v lumen >/dev/null 2>&1; then
    echo "[lab-local] fallback installed lumen"
    exec lumen science lab --addr "$ADDR" --no-browser
  fi
  echo "[lab-local] ERROR: neither go nor lumen found" >&2
  exit 1
}

if [[ "${SMOKE:-0}" == "1" ]]; then
  # Parse host:port from ADDR
  PORT="${ADDR##*:}"
  HOST_PART="${ADDR%:*}"
  # Free port if needed
  if lsof -tiTCP:"$PORT" -sTCP:LISTEN >/dev/null 2>&1; then
    echo "[lab-local] port $PORT busy — smoke will use existing server if healthy"
    if curl -sS "http://127.0.0.1:${PORT}/api/lab/health" >/tmp/lab-smoke-health.json 2>/dev/null; then
      python3 - <<'PY'
import json
h=json.load(open("/tmp/lab-smoke-health.json"))
lg=h.get("langgraph") or {}
oo=h.get("onlyoffice") or {}
print("[smoke] existing health langgraph.available=", lg.get("available"), "onlyoffice.configured=", oo.get("configured"))
PY
      exit 0
    fi
    echo "[lab-local] existing listener not healthy; free the port and re-run" >&2
    exit 1
  fi
  # Background lab, health-check, then stop
  go run ./cmd/lumen science lab --addr "$ADDR" --no-browser >/tmp/lumen-lab-smoke.log 2>&1 &
  lab_pid=$!
  cleanup() { kill "$lab_pid" 2>/dev/null || true; }
  trap cleanup EXIT
  ok=0
  for i in $(seq 1 40); do
    if curl -sS "http://127.0.0.1:${PORT}/api/lab/health" >/tmp/lab-smoke-health.json 2>/dev/null; then
      ok=1
      break
    fi
    sleep 0.5
  done
  if [[ "$ok" != "1" ]]; then
    echo "[smoke] FAIL: lab did not become healthy" >&2
    tail -40 /tmp/lumen-lab-smoke.log >&2 || true
    exit 1
  fi
  python3 - <<'PY'
import json, os, sys
h=json.load(open("/tmp/lab-smoke-health.json"))
lg=h.get("langgraph") or {}
oo=h.get("onlyoffice") or {}
print("[smoke] langgraph.available =", lg.get("available"), "hint =", lg.get("hint"))
print("[smoke] onlyoffice.configured =", oo.get("configured"), "url =", oo.get("url"))
# Soft expectations when sidecars were detected at start
want_lg = os.environ.get("LUMEN_LANGGRAPH") == "1"
want_oo = bool(os.environ.get("LUMEN_ONLYOFFICE_URL"))
errs=[]
if want_lg and not lg.get("available"):
  errs.append("LangGraph enabled but health.available=false")
if want_oo and not oo.get("configured"):
  errs.append("OnlyOffice URL set but health.configured=false")
if errs:
  print("[smoke] FAIL:", "; ".join(errs), file=sys.stderr)
  sys.exit(1)
print("[smoke] PASS")
PY
  if [[ -n "${LUMEN_LANGGRAPH:-}" ]]; then
    curl -sS -X POST "http://127.0.0.1:${PORT}/api/lab/langgraph/run" \
      -H 'Content-Type: application/json' \
      -d '{"project_id":"smoke","prompt":"sidecar smoke"}' | python3 -m json.tool
  fi
  exit 0
fi

run_lab
