#!/usr/bin/env bash
# Small-step science test runner — avoids hanging on stress tests.
set -euo pipefail
cd "$(dirname "$0")/.."
TIMEOUT="${TIMEOUT:-30s}"
PKGS=(
  ./internal/science/proxy/...
  ./internal/science/config/...
  ./internal/science/runtime/...
  ./internal/science/migrate/...
  ./internal/science/mcp/...
  ./internal/science/native/...
  ./internal/science/oauth/...
  ./internal/science/research/...
  ./internal/science/gui/...
)
echo "▶ science quick verify (-short, timeout=${TIMEOUT})"
for pkg in "${PKGS[@]}"; do
  echo "  · ${pkg}"
  go test "$pkg" -count=1 -short -timeout "$TIMEOUT"
done
echo "✓ all packages passed"